
#DEV CONSTS
PYDEVD_EGG = r"C:\Program Files\JetBrains\PyCharm 2020.3.3\debug-eggs\pydevd-pycharm.egg"

#MAYA CONSTS
MTL_NS = "mtls"
TMP_NS = "temp_namespace_qazwsx"

STEM_MTL_NAME = "plant_mtl"
SPIKES_MTL_NAME = "spikes_mtl"

SUBDIV_CATCLARK = 1
SUBDIV_LINEAR = 2

BIND_METHOD_CLOSEST_JOINT_TO_GEO = 0
BIND_METHOD_CLOSEST_CONSIDER_SKELETON = 1
BIND_METHOD_SURFACE_HEATMAP = 2
BIND_METHOD_GEODESIC_VOXELS = 3

SKIN_METHOD_LINEAR = 0
SKIN_METHOD_DUAL_QUATERNION = 1
SKIN_METHOD_MIXED = 2
